### ISSUE TITLE
do_cosine_sim.kv compatibility with tidyr@1.0.0

### ISSUE THREAD

**Issue by lchski** [exploratory-io/exploratory_func#659]
`do_cosine_sim.kv` doesn’t work under `tidyr@1.0.0`. Running the function with a dataset that should work fine (a bit tricky to share, but can if need be—just creating the issue to note this is a problem) generates the following:

```
Error: `unnest_()` is deprecated as of tidyr 1.0.0.
Please use `unnest()` instead. 
```

**Comment by hideaki** [comment]
Thank you for filing issue.
We are working on making it work with tidyr@1.0.0 in general right now.

**Comment by hideaki** [comment]
We adjusted tidyr calls for tidyr@1.0.0. This should work fine with the latest releases of Exploratory.
